/**
 * BridgeProxy Contract ABI
 *
 * Handles deposit/buy and sell operations for bridged ITP tokens.
 * Extracted from: bridge/bridge-contracts/out/BridgeProxy.sol/BridgeProxy.json
 */

export const bridgeProxyAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_bridge', type: 'address', internalType: 'address' },
      { name: '_usdc', type: 'address', internalType: 'address' },
      { name: '_factory', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'completeBuy',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'itpAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'completeSell',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'usdcAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'depositForBuy',
    inputs: [
      { name: 'targetItp', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'factory',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract BridgedItpFactory' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPendingDeposit',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct BridgeProxy.PendingDeposit',
        components: [
          { name: 'user', type: 'address', internalType: 'address' },
          { name: 'targetItp', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'completed', type: 'bool', internalType: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPendingSell',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'nonce', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct BridgeProxy.PendingSell',
        components: [
          { name: 'user', type: 'address', internalType: 'address' },
          { name: 'itpAddress', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'completed', type: 'bool', internalType: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserDepositNonce',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserSellNonce',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingDeposits',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'targetItp', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'completed', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingSells',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'itpAddress', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'completed', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestSell',
    inputs: [
      { name: 'itpAddress', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'usdc',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'userDepositNonce',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'userSellNonce',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'BuyCompleted',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'itpAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'nonce',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositForBuy',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'targetItp',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'nonce',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SellCompleted',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'usdcAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'nonce',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SellRequested',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'itpAddress',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'nonce',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'DepositAlreadyCompleted', inputs: [] },
  { type: 'error', name: 'DepositNotFound', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'InvalidFactoryAddress', inputs: [] },
  { type: 'error', name: 'InvalidItpAddress', inputs: [] },
  { type: 'error', name: 'InvalidTargetItp', inputs: [] },
  { type: 'error', name: 'InvalidUsdcAddress', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'SellAlreadyCompleted', inputs: [] },
  { type: 'error', name: 'SellNotFound', inputs: [] },
  { type: 'error', name: 'BridgedItpNotFound', inputs: [] },
  { type: 'error', name: 'ItpCreationNotFound', inputs: [] },
  { type: 'error', name: 'ItpCreationAlreadyCompleted', inputs: [] },
  { type: 'error', name: 'InvalidTokenName', inputs: [] },
  { type: 'error', name: 'InvalidTokenSymbol', inputs: [] },
  { type: 'error', name: 'InvalidAssets', inputs: [] },
  { type: 'error', name: 'AssetWeightMismatch', inputs: [] },
  { type: 'error', name: 'SellAlreadyRefunded', inputs: [] },
  { type: 'error', name: 'DepositAlreadyRefunded', inputs: [] },
  // ITP Creation functions
  {
    type: 'function',
    name: 'requestCreateItp',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'symbol', type: 'string', internalType: 'string' },
      { name: 'description', type: 'string', internalType: 'string' },
      { name: 'methodology', type: 'string', internalType: 'string' },
      { name: 'initialPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'maxOrderSize', type: 'uint128', internalType: 'uint128' },
      { name: 'assets', type: 'uint128[]', internalType: 'uint128[]' },
      { name: 'weights', type: 'uint128[]', internalType: 'uint128[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getAdminItpCreationNonce',
    inputs: [{ name: 'admin', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'adminItpCreationNonce',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'CreateItpRequested',
    inputs: [
      { name: 'admin', type: 'address', indexed: true, internalType: 'address' },
      { name: 'name', type: 'string', indexed: false, internalType: 'string' },
      { name: 'symbol', type: 'string', indexed: false, internalType: 'string' },
      { name: 'description', type: 'string', indexed: false, internalType: 'string' },
      { name: 'methodology', type: 'string', indexed: false, internalType: 'string' },
      { name: 'initialPrice', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'maxOrderSize', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'assets', type: 'uint128[]', indexed: false, internalType: 'uint128[]' },
      { name: 'weights', type: 'uint128[]', indexed: false, internalType: 'uint128[]' },
      { name: 'nonce', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ItpCreated',
    inputs: [
      { name: 'orbitItp', type: 'address', indexed: true, internalType: 'address' },
      { name: 'arbitrumBridgedItp', type: 'address', indexed: true, internalType: 'address' },
      { name: 'nonce', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
] as const;
