/*
 Generated by typeshare 1.13.4

 MANUAL MODIFICATIONS (do not regenerate without preserving):
 - id field changed from `number` to `bigint` for u128 compatibility
 - Added helper functions for ID conversion (assetIdToBigInt, assetIdToNumber)
 - Added AssetJSON type for JSON deserialization (IDs come as numbers in JSON)

 To regenerate from Rust: typeshare --lang typescript libs/asset-registry/src/types.rs -o indexmaker_frontend/lib/types/assets.ts
 Then manually restore the bigint handling and helper functions.
*/

/**
 * Represents a tradeable asset with mappings to external systems
 *
 * @remarks
 * - `id`: On-chain asset identifier (u128 - stored as bigint in TypeScript)
 * - `coingecko`: CoinGecko identifier for price feeds (e.g., "bitcoin", "ethereum")
 * - `bitget`: Bitget trading pair symbol (e.g., "BTCUSDC", "ETHUSDC")
 * - `logo`: URL to the asset's logo image (optional)
 */
export interface Asset {
  /**
   * On-chain asset ID - MUST be u128 to match vaultworks contracts.
   * Use bigint for type safety with large IDs.
   */
  id: bigint;

  /**
   * CoinGecko identifier for price data
   * May be empty string if no CoinGecko mapping exists
   */
  coingecko: string;

  /** Bitget trading pair symbol (e.g., "BTCUSDC") */
  bitget: string;

  /**
   * URL to the asset's logo image
   * May be empty string if no logo is available
   */
  logo?: string;
}

/**
 * Asset as it appears in JSON (IDs are numbers, not bigint)
 * Use this type when parsing JSON, then convert to Asset
 */
export interface AssetJSON {
  id: number;
  coingecko: string;
  bitget: string;
  logo?: string;
}

/**
 * Convert an AssetJSON to Asset (number id -> bigint id)
 */
export function assetFromJSON(json: AssetJSON): Asset {
  return {
    ...json,
    id: BigInt(json.id),
  };
}

/**
 * Convert an array of AssetJSON to Asset[]
 */
export function assetsFromJSON(json: AssetJSON[]): Asset[] {
  return json.map(assetFromJSON);
}

/**
 * Helper to convert asset ID to bigint for safe handling of large values
 * @deprecated Use Asset.id directly (already bigint) or assetFromJSON for JSON parsing
 */
export function assetIdToBigInt(id: bigint | number | string): bigint {
  if (typeof id === "bigint") return id;
  return BigInt(id);
}

/**
 * Helper to convert asset ID to number (use only when you know the ID fits in Number.MAX_SAFE_INTEGER)
 */
export function assetIdToNumber(id: bigint): number {
  const num = Number(id);
  if (!Number.isSafeInteger(num)) {
    console.warn(`Asset ID ${id} exceeds safe integer range`);
  }
  return num;
}
